replicaCount: 1

image:
  repository: shogungoose/webtest-capybara
  pullPolicy: Always
  tag: dev-latest

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "traefic"
  host: dev.rpi.local
  path: /
