name: Deploy RaspberryPi

on:
  push:
    branches:
      - dev
      - prod

  workflow_run:
    workflows:
      - "build"
    types:
      - completed
  
jobs:

  deploy:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' && 
       github.event.workflow_run.conclusion == 'success')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH connection
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        script: |
          echo "### Deploying to ${{ github.ref }} ###"
          cd /home/ci/webtest-capybara || exit 1

          git fetch origin ${{ github.ref_name }}
          git reset --hard origin/${{ github.ref_name }}
          git checkout ${{ github.ref_name }}
          git pull origin ${{ github.ref_name }}

          echo "=> Deploying ${{ github.ref_name }}"
          helm upgrade --install http-server-${{ github.ref_name }} ./Chart -f Chart/values-${{ github.ref_name }}.yaml -n ${{ github.ref_name }} --create-namespace
