name: CI/CD

on:
    push:
        branches:
            - dev
            - main

jobs:
    detect:
        runs-on: ubuntu-latest
        outputs:
            go_changed: ${{ steps.filter.outputs.go }}
        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  filters: |
                      go:
                        - '**/*.go'
                        - 'go.mod'
                        - 'go.sum'
                        - 'Dockerfile'
            - name: Debug show filter output
              run: echo "filter.go=${{ steps.filter.outputs.go }}"

    build:
        needs: detect
        if: needs.detect.outputs.go_changed == 'true'
        uses: ./.github/workflows/build-dev.yml

    deploy:
        needs:
            - detect
#            - build
        #if: needs.detect.outputs.go_changed == 'false' || needs.build.result == 'success'
        if: needs.detect.outputs.go_changed == 'false'
        runs-on: ubuntu-latest
        steps:
            - name: Debug needs
              run: echo "needs.detect.outputs.go_changed=${{ needs.detect.outputs.go_changed }}"
        #uses: ./.github/workflows/deploy-raspberry.yml
